### PR TITLE
NOISSUE - Resolve falsely passing CI

### PR DESCRIPTION
**Pull request by Musilah**
# What type of PR is this?

## What does this do?
This is a CI Fix that stops the CI  from passing should any tests fail.

## Which issue(s) does this PR fix/relate to?

None.
## Have you included tests for your changes?
No.

## Did you document any new/modified feature?
No.

### CODE REVIEW

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Let's not continue on error in any case.

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Do we need this in tests?
```yml
    continue-on-error: false
    strategy:
      fail-fast: true
```

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

**Review by rodneyosodo — APPROVED** [review]
LGTM

**Review by arvindh123 — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
